# Generated by Django 5.1 on 2024-08-13 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_admin',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_branch_manager',
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('branch_manager', 'Branch Manager'), ('admin', 'Admin')], default='', max_length=20),
            preserve_default=False,
        ),
    ]
