# Generated by Django 5.1 on 2024-08-11 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0002_alter_branch_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branch',
            options={'ordering': ('name',), 'verbose_name': 'Branch', 'verbose_name_plural': 'Branches'},
        ),
        migrations.AlterModelOptions(
            name='productrequest',
            options={'ordering': ('-date_requested',)},
        ),
    ]
