# Generated by Django 5.1 on 2024-08-17 07:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0003_alter_branch_options_alter_productrequest_options'),
        ('products', '0005_product_barcode_image_alter_product_opening_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productrequest',
            name='fulfilled',
        ),
        migrations.AddField(
            model_name='productrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('acknowledged', 'Acknowledged'), ('fulfilled', 'Fulfilled')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='BranchProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_products', to='branches.branch')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_products', to='products.product')),
            ],
            options={
                'ordering': ('product__name',),
                'unique_together': {('branch', 'product')},
            },
        ),
    ]
