# Generated by Django 5.1 on 2024-08-18 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0005_branchproduct_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='branch_code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
