# Generated by Django 5.1 on 2024-08-13 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_productinflow_expiry_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinflow',
            name='date_received',
            field=models.DateField(auto_now_add=True),
        ),
    ]
