# Generated by Django 5.1 on 2024-08-13 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_alter_productoutflow_date_sent'),
        ('suppliers', '0002_alter_supplier_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinflow',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suppliers.supplier'),
        ),
    ]
