# Generated by Django 5.1 on 2024-08-11 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_category_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='damagedproduct',
            options={'ordering': ('-date_reported',)},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('name',)},
        ),
    ]
