# Generated by Django 5.1 on 2024-08-15 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_product_expiry_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='barcode_image',
            field=models.ImageField(blank=True, null=True, upload_to='barcodes/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='opening_stock',
            field=models.PositiveIntegerField(),
        ),
    ]
